#!/bin/bash
YELLOW='\033[1;33m'
NC='\033[0m' # No Color


echo -e "${YELLOW}Adding NGINX to ~/.bashrc${NC} \n"
sudo cat >> ~/.bashrc <<EOL 
if [[ -n \$SSH_CONNECTION ]] ; then 
    sudo systemctl start nginx 
    echo "Starting NGINX server for TINYPILOT KVM" 
fi
EOL
sleep .5

#PAGE BREAK

echo -e "${YELLOW}NGINX Halt at ssh session termination${NC} \n"
sudo /bin/sh -c 'echo "session     optional    pam_exec.so quiet /etc/pam_session.sh" >> /etc/pam.d/sshd'
sleep .5

#PAGE BREAK

echo -e "${YELLOW}Downloading pam_session.sh -> /etc/${NC} \n"
sudo wget -q -P /etc/ https://raw.githubusercontent.com/westleypeltondhp/dhp-tinypilot-kvm/main/pam_session.sh
sleep .5

#PAGE BREAK

echo -e "${YELLOW}Making pam_session.sh executable...${NC} \n"
sudo chmod a+x /etc/pam_session.sh
sleep .5

#PAGE BREAK

echo -e "${YELLOW}COMPLETE!${NC} \n"
