#!/usr/bin/env bash

sudo chown pi /opt/tinypilot-privileged/update

sudo cat >> /opt/tinypilot-privileged/update <<EOL 
https://raw.githubusercontent.com/westleypeltondhp/dhp-tinypilot-kvm/main/dhpkvm-tp_update_modifier | \
    bash -
sudo systemctl disable nginx
EOL

sudo chown tinypilot /opt/tinypilot-privileged/update