#!/usr/bin/env bash

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#BREAK!

echo -e "${YELLOW}CHOWN'ing /opt/tinypilot-privileged/update${NC} \n"
sudo chown pi /opt/tinypilot-privileged/update
sleep .5

#BREAK!

echo -e "${YELLOW}RE-Adding DHP TP Script -> /opt/tinypilot-privileged/update${NC} \n"
sudo cat >> /opt/tinypilot-privileged/update <<EOL
curl \
  --silent \
  --show-error \
https://raw.githubusercontent.com/westleypeltondhp/dhp-tinypilot-kvm/main/dhpkvm-tp_update_modifier | \
    bash -
sudo systemctl disable nginx
EOL
sleep .5

#BREAK!

echo -e "${YELLOW}Make tinypilot file owner again...${NC} \n"
sudo chown tinypilot /opt/tinypilot-privileged/update
sleep .5

#BREAK!

echo -e "${YELLOW}DHP-TP Updater Modifier COMPLETE!...${NC} \n"
