#!/usr/bin/env bash

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#BREAK!

echo -e "${YELLOW}What is your name?${NC} \n"
read name

echo -e "${YELLOW}How do you do, $name?${NC} \n"
read remark

echo -e "${YELLOW}I am $remark too!${NC} \n"