#!/bin/sh

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

#BREAK!

read -r -p "What is your Duo Integration Key?: " ikey1
sudo sed -i '/ikey =/ s/$/"$ikey1" /' ~/login_duo.conf
echo "${YELLOW}Added ikey...${NC} \n"
sleep .5

read -r -p "What is your Duo Secret Key?: " skey1
sudo sed -i '/skey =/ s/$/"$skey1" /' ~/login_duo.conf
echo "${YELLOW}Added skey...${NC} \n"
sleep .5

read -r -p "What is your Duo API host?: " host1
sudo sed -i '/host =/ s/$/"$host1" /' ~/login_duo.conf
echo "${YELLOW}Added host...${NC} \n"
sleep .5